### PR TITLE
Do not use strict version constraints in pyproject.toml

### PR DESCRIPTION
**Pull request by AngellusMortis**
Fixes https://github.com/DataDog/guarddog/issues/79

### CODE REVIEW

**Comment by AngellusMortis** [comment]
I also updated the requirements using [poetry export](https://python-poetry.org/docs/cli/#export) which seems to be the way you are suppose to do it. I do not know if you guys were updating it before. I also do not really have any experience with poetry either.

**Comment by christophetd** [comment]
Thanks for the contribution, looks like the CI is failing though. Let me know if you need help fixing it

**Review by christophetd — APPROVED** [review]

**Comment by AngellusMortis** [comment]
Is there a change we can get a new PyPi release now? It looks like there has not been one since March and there has been a number of new changes (outside of just this one).

**Comment by christophetd** [comment]
I was hoping to merge a few more PRs before a release, but since it has taken more time than anticipated, no objection - thanks for the nudge!

**Pull request merged**
