### PR TITLE
pyproject.toml: Add repository url

### PR DESCRIPTION
**Pull request by materro**
Add missing project link to PyPi.

### CODE REVIEW

**Comment by christophetd** [comment]
Thanks!

**Review by christophetd — APPROVED** [review]

**Comment by christophetd** [comment]
Won't release a new version for this change, so it will show up in the next release

**Comment by materro** [comment]
Would You also like to add
homepage = "https://securitylabs.datadoghq.com/articles/guarddog-identify-malicious-pypi-packages/"
and
documentation = "https://github.com/DataDog/guarddog"
?
https://python-poetry.org/docs/pyproject/#homepage

**Comment by christophetd** [comment]
The homepage should still be the GitHub repository. And I think people can easily figure out where to find docs from the GitHub repository

**Pull request merged**
